site_name: notebOOOOOOk
theme:
  name: readthedocs
markdown_extensions:
  - toc:
      toc_depth: 1-6
      permalink: true
  - fenced_code
  - tables
  - footnotes
  - def_list
  - attr_list
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.mark
extra_javascript:
  - js/code-copy.js
extra_css:
  - styles/code-copy.css
nav:
  - Home: index.md
  - EDA:
      - EDA: EDA.md
      - PR-Analog: PR-Analog.md
      - PR-Digtal: PR-Digtal.md
      - PR-LCM: PR-LCM.md
      - Flow: flow.md
  - Tools:
      - Algorithms: Algorithms.md
      - Hardware: Hardware.md
      - OS: OS.md
      - Program: Program.md
      - Tools: Tools.md
  - Other:
      - Good Things: Literature.md
